sonar.projectKey=SMAR-IA
sonar.projectName=SMAR-IA - Sistema Inteligente de Detección y Mitigación
sonar.projectVersion=1.0.0

sonar.sources=backend,ml_pipeline
sonar.tests=backend
sonar.test.inclusions=backend/test_*.py
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/venv/**,**/benchmark/**,**/logs/**,**/alembic/**,**/models/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml

sonar.sourceEncoding=UTF-8
sonar.language=py

sonar.host.url=https://sonarcloud.io
sonar.organization=74902142-star
