"""initial_models

Revision ID: eae768a83d0e
Revises: 
Create Date: 2026-06-09 19:46:22.484753
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'eae768a83d0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
